name: Java CI with Maven

on:
  push:
    branches: [ "main", "feature/Homework_6" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Print time to console
        run: |
          date +"%Y-%m-%d"

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: build with Maven
        run: mvn install -B -D skipTests

      - name: Run tests
        run: mvn test

      - name: Verify code coverage
        run: mvn verify